package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"stub-subgraph/generated"
	"stub-subgraph/model"
)

// FindOrderByID is the resolver for the findOrderByID field.
func (r *entityResolver) FindOrderByID(ctx context.Context, id string) (*model.Order, error) {
	return &model.Order{
		ID:                  id,
		Title:               "Stub order",
		Owner:               &model.User{ID: ownerIDFromContext(ctx)},
		SeenIdentityHeaders: identityHeaders(ctx),
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
