package main

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"stub-subgraph/generated"
	"stub-subgraph/model"
)

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context) ([]*model.Order, error) {
	return []*model.Order{{
		ID:                  "order-1",
		Title:               "Stub order",
		Owner:               &model.User{ID: ownerIDFromContext(ctx)},
		SeenIdentityHeaders: identityHeaders(ctx),
	}}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
