// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Application struct {
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
	Roles       []*Role  `json:"roles"`
}

type AuditEntry struct {
	ID           string  `json:"id"`
	Actor        string  `json:"actor"`
	Action       string  `json:"action"`
	TargetUserID *string `json:"targetUserId,omitempty"`
	// JSON-encoded action details
	Details   string    `json:"details"`
	CreatedAt time.Time `json:"createdAt"`
}

// Current viewer with effective permissions.
type Me struct {
	User        *User    `json:"user"`
	Permissions []string `json:"permissions"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Query struct {
}

type Role struct {
	Application string   `json:"application"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

type RoleAssignment struct {
	Application string    `json:"application"`
	Role        string    `json:"role"`
	GrantedBy   string    `json:"grantedBy"`
	GrantedAt   time.Time `json:"grantedAt"`
}

// Unified application user; referenced by GSH/DFM subgraphs by global id.
type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
	// Job title from provisioning; empty when unknown.
	Title        string            `json:"title"`
	Active       bool              `json:"active"`
	LastSignInAt *time.Time        `json:"lastSignInAt,omitempty"`
	Roles        []*RoleAssignment `json:"roles"`
}

func (User) IsEntity() {}

// A page of users. Cursors are opaque; pass endCursor as `after` for the
// next page.
type UserConnection struct {
	Nodes    []*User   `json:"nodes"`
	PageInfo *PageInfo `json:"pageInfo"`
}
