// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// A message between two users. Author and recipient are references into the
// identity subgraph: this service stores only their global ids and the
// router resolves the rest.
type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	Author    *User     `json:"author"`
	Recipient *User     `json:"recipient"`
	SentAt    time.Time `json:"sentAt"`
}

func (Message) IsEntity() {}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
