package main

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"messenger/generated"
	"messenger/model"
)

// FindMessageByID is the resolver for the findMessageByID field.
func (r *entityResolver) FindMessageByID(ctx context.Context, id string) (*model.Message, error) {
	if err := requireUser(identityFrom(ctx)); err != nil {
		return nil, gqlError(ctx, err)
	}
	m, ok := r.store.Find(id)
	if !ok {
		return nil, fmt.Errorf("message %s not found", id)
	}
	return m, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
