package main

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"messenger/generated"
	"messenger/model"
)

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, recipientID string, text string) (*model.Message, error) {
	id := identityFrom(ctx)
	if err := requireSend(id); err != nil {
		return nil, gqlError(ctx, err)
	}
	return r.store.Send(id.UserID, recipientID, text), nil
}

// Inbox is the resolver for the inbox field.
func (r *queryResolver) Inbox(ctx context.Context) ([]*model.Message, error) {
	id := identityFrom(ctx)
	if err := requireUser(id); err != nil {
		return nil, gqlError(ctx, err)
	}
	return r.store.Inbox(id.UserID), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
