{{- if .Values.dbmigrate.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "identity-service.fullname" . }}-migrate
  labels:
    {{- include "identity-service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "argocd.argoproj.io/sync-wave": "-1"
spec:
  backoffLimit: {{ .Values.dbmigrate.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.dbmigrate.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ .Values.dbmigrate.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "identity-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "identity-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- include "identity-service.env" . | nindent 10 }}
          resources:
            {{- toYaml .Values.dbmigrate.resources | nindent 12 }}
{{- end }}
