package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/xometry-europe-gmbh/identity-service/internal/graphql/generated"
	"github.com/xometry-europe-gmbh/identity-service/internal/graphql/model"
	"github.com/xometry-europe-gmbh/identity-service/internal/identity"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	user, err := r.Directory.FindByID(ctx, id)
	if errors.Is(err, identity.ErrUserNotFound) {
		return nil, errWithCode("user not found", "BAD_USER_INPUT")
	}
	if err != nil {
		r.Logger.Error("entity lookup failed", "error", err)
		return nil, errWithCode("entity lookup failed", "INTERNAL")
	}
	return toModelUser(user), nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
