package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/xometry-europe-gmbh/identity-service/internal/access"
	"github.com/xometry-europe-gmbh/identity-service/internal/graphql/generated"
	"github.com/xometry-europe-gmbh/identity-service/internal/graphql/model"
	"github.com/xometry-europe-gmbh/identity-service/internal/identity"
)

// GrantRole is the resolver for the grantRole field.
func (r *mutationResolver) GrantRole(ctx context.Context, userID string, role string) (*model.User, error) {
	return r.changeRole(ctx, userID, role, true)
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, role string) (*model.User, error) {
	return r.changeRole(ctx, userID, role, false)
}

func (r *mutationResolver) changeRole(ctx context.Context, userID, roleRef string, grant bool) (*model.User, error) {
	viewer, err := requireManage(ctx)
	if err != nil {
		return nil, err
	}
	app, role, err := access.SplitRoleRef(roleRef)
	if err != nil {
		return nil, errWithCode(err.Error(), "BAD_USER_INPUT")
	}

	if grant {
		err = r.Access.GrantRole(ctx, viewer.User.ID, userID, app, role)
	} else {
		err = r.Access.RevokeRole(ctx, viewer.User.ID, userID, app, role)
	}
	switch {
	case errors.Is(err, access.ErrRoleNotFound):
		return nil, errWithCode(err.Error(), "BAD_USER_INPUT")
	case err != nil:
		r.Logger.Error("role change failed", "error", err)
		return nil, errWithCode("role change failed", "INTERNAL")
	}

	user, err := r.Directory.FindByID(ctx, userID)
	if errors.Is(err, identity.ErrUserNotFound) {
		return nil, errWithCode("user not found", "BAD_USER_INPUT")
	}
	if err != nil {
		r.Logger.Error("user lookup failed", "error", err)
		return nil, errWithCode("user lookup failed", "INTERNAL")
	}
	return toModelUser(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Me{User: toModelUser(viewer.User), Permissions: viewer.Permissions}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, search *string, includeInactive bool) ([]*model.User, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	term := ""
	if search != nil {
		term = *search
	}
	users, err := r.Directory.SearchUsers(ctx, term, includeInactive, maxUsersPage)
	if err != nil {
		r.Logger.Error("user search failed", "error", err)
		return nil, errWithCode("user search failed", "INTERNAL")
	}
	out := make([]*model.User, len(users))
	for i, u := range users {
		out[i] = toModelUser(u)
	}
	return out, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	user, err := r.Directory.FindByID(ctx, id)
	if errors.Is(err, identity.ErrUserNotFound) {
		return nil, nil
	}
	if err != nil {
		r.Logger.Error("user lookup failed", "error", err)
		return nil, errWithCode("user lookup failed", "INTERNAL")
	}
	return toModelUser(user), nil
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context) ([]*model.Application, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	apps, err := r.Access.ListApplications(ctx)
	if err != nil {
		r.Logger.Error("application listing failed", "error", err)
		return nil, errWithCode("application listing failed", "INTERNAL")
	}
	out := make([]*model.Application, len(apps))
	for i, app := range apps {
		roles := make([]*model.Role, len(app.Roles))
		for j, role := range app.Roles {
			roles[j] = &model.Role{Application: role.Application, Name: role.Name, Permissions: role.Permissions}
		}
		out[i] = &model.Application{Name: app.Name, Permissions: app.Permissions, Roles: roles}
	}
	return out, nil
}

// AccessAuditLog is the resolver for the accessAuditLog field.
func (r *queryResolver) AccessAuditLog(ctx context.Context, limit int) ([]*model.AuditEntry, error) {
	if _, err := requireManage(ctx); err != nil {
		return nil, err
	}
	limit = min(max(limit, 1), maxAuditPage)
	entries, err := r.Access.AuditEntries(ctx, limit)
	if err != nil {
		r.Logger.Error("audit log read failed", "error", err)
		return nil, errWithCode("audit log read failed", "INTERNAL")
	}
	out := make([]*model.AuditEntry, len(entries))
	for i, e := range entries {
		entry := &model.AuditEntry{
			ID:        e.ID,
			Actor:     e.Actor,
			Action:    e.Action,
			Details:   e.Details,
			CreatedAt: e.CreatedAt,
		}
		if e.TargetUserID != "" {
			target := e.TargetUserID
			entry.TargetUserID = &target
		}
		out[i] = entry
	}
	return out, nil
}

// Roles is the resolver for the roles field.
func (r *userResolver) Roles(ctx context.Context, obj *model.User) ([]*model.RoleAssignment, error) {
	assignments, err := r.Access.UserAssignments(ctx, obj.ID)
	if err != nil {
		r.Logger.Error("assignments lookup failed", "error", err)
		return nil, errWithCode("assignments lookup failed", "INTERNAL")
	}
	out := make([]*model.RoleAssignment, len(assignments))
	for i, a := range assignments {
		out[i] = &model.RoleAssignment{
			Application: a.Application,
			Role:        a.Role,
			GrantedBy:   a.GrantedBy,
			GrantedAt:   a.GrantedAt,
		}
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

func toModelUser(u *identity.User) *model.User {
	return &model.User{
		ID:           u.ID,
		Email:        u.Email,
		Name:         u.Name,
		Active:       u.Active,
		LastSignInAt: u.LastSignInAt,
	}
}
