package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/paderinandrey/identity-service/internal/graphql/generated"
	"github.com/paderinandrey/identity-service/internal/graphql/model"
	"github.com/paderinandrey/identity-service/internal/identity"
)

// GrantRole is the resolver for the grantRole field.
func (r *mutationResolver) GrantRole(ctx context.Context, userID string, role string) (*model.User, error) {
	return r.changeRole(ctx, userID, role, true)
}

// RevokeRole is the resolver for the revokeRole field.
func (r *mutationResolver) RevokeRole(ctx context.Context, userID string, role string) (*model.User, error) {
	return r.changeRole(ctx, userID, role, false)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}
	return &model.Me{User: toModelUser(viewer.User), Permissions: viewer.Permissions}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, search *string, includeInactive bool, first int, after *string) (*model.UserConnection, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	if first < 1 || first > maxUsersPage {
		return nil, errWithCode("first must be between 1 and 200", "BAD_USER_INPUT")
	}
	// Only an omitted/null cursor means the first page: an empty string
	// was never issued by the service, so it is invalid like any other
	// unknown value (Codex review, PR #7).
	var afterKey *identity.PageKey
	if after != nil {
		key, err := decodeCursor(*after)
		if err != nil {
			return nil, errWithCode(err.Error(), "BAD_USER_INPUT")
		}
		afterKey = key
	}
	term := ""
	if search != nil {
		term = *search
	}
	// One row more than the page tells whether a next page exists.
	users, err := r.Directory.SearchUsers(ctx, term, includeInactive, afterKey, first+1)
	if err != nil {
		r.Logger.Error("user search failed", "error", err)
		return nil, errWithCode("user search failed", "INTERNAL")
	}
	hasNext := len(users) > first
	if hasNext {
		users = users[:first]
	}

	// The page's assignments in one query, handed to User.roles through
	// the request-scoped prefetch instead of one query per user.
	ids := make([]string, len(users))
	for i, u := range users {
		ids[i] = u.ID
	}
	assignments, err := r.Access.AssignmentsForUsers(ctx, ids)
	if err != nil {
		r.Logger.Error("assignments lookup failed", "error", err)
		return nil, errWithCode("assignments lookup failed", "INTERNAL")
	}
	prefetchFrom(ctx).put(assignments, ids)

	nodes := make([]*model.User, len(users))
	for i, u := range users {
		nodes[i] = toModelUser(u)
	}
	page := &model.PageInfo{HasNextPage: hasNext}
	if len(users) > 0 {
		cursor := encodeCursor(users[len(users)-1])
		page.EndCursor = &cursor
	}
	return &model.UserConnection{Nodes: nodes, PageInfo: page}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	user, err := r.Directory.FindByID(ctx, id)
	if errors.Is(err, identity.ErrUserNotFound) {
		return nil, nil
	}
	if err != nil {
		r.Logger.Error("user lookup failed", "error", err)
		return nil, errWithCode("user lookup failed", "INTERNAL")
	}
	return toModelUser(user), nil
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context) ([]*model.Application, error) {
	if _, err := requireViewer(ctx); err != nil {
		return nil, err
	}
	apps, err := r.Access.ListApplications(ctx)
	if err != nil {
		r.Logger.Error("application listing failed", "error", err)
		return nil, errWithCode("application listing failed", "INTERNAL")
	}
	out := make([]*model.Application, len(apps))
	for i, app := range apps {
		roles := make([]*model.Role, len(app.Roles))
		for j, role := range app.Roles {
			roles[j] = &model.Role{Application: role.Application, Name: role.Name, Permissions: role.Permissions}
		}
		out[i] = &model.Application{Name: app.Name, Permissions: app.Permissions, Roles: roles}
	}
	return out, nil
}

// AccessAuditLog is the resolver for the accessAuditLog field.
func (r *queryResolver) AccessAuditLog(ctx context.Context, limit int) ([]*model.AuditEntry, error) {
	if _, err := requireManage(ctx); err != nil {
		return nil, err
	}
	limit = min(max(limit, 1), maxAuditPage)
	entries, err := r.Access.AuditEntries(ctx, limit)
	if err != nil {
		r.Logger.Error("audit log read failed", "error", err)
		return nil, errWithCode("audit log read failed", "INTERNAL")
	}
	out := make([]*model.AuditEntry, len(entries))
	for i, e := range entries {
		entry := &model.AuditEntry{
			ID:        e.ID,
			Actor:     e.Actor,
			Action:    e.Action,
			Details:   e.Details,
			CreatedAt: e.CreatedAt,
		}
		if e.TargetUserID != "" {
			target := e.TargetUserID
			entry.TargetUserID = &target
		}
		out[i] = entry
	}
	return out, nil
}

// Roles is the resolver for the roles field.
func (r *userResolver) Roles(ctx context.Context, obj *model.User) ([]*model.RoleAssignment, error) {
	if assignments, ok := prefetchFrom(ctx).get(obj.ID); ok {
		return toModelAssignments(assignments), nil
	}
	// Single-user paths (user, _entities, mutations) load on demand.
	assignments, err := r.Access.UserAssignments(ctx, obj.ID)
	if err != nil {
		r.Logger.Error("assignments lookup failed", "error", err)
		return nil, errWithCode("assignments lookup failed", "INTERNAL")
	}
	return toModelAssignments(assignments), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
