// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID                  string   `json:"id"`
	Title               string   `json:"title"`
	Owner               *User    `json:"owner"`
	SeenIdentityHeaders []string `json:"seenIdentityHeaders"`
}

func (Order) IsEntity() {}

type Query struct {
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
